version: "3.9"

services:
  redis:
    image: redis
    environment:
      - TZ=America/Sao_Paulo

  api:
    build:
      context: .
      args:
        DEVPI_HOST: ${DEVPI_HOST}
        DEVPI_USER: ${DEVPI_USER}
        DEVPI_PASSWORD: ${DEVPI_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./app:/project/app
      - ./app/htmlcov:/project/app/htmlcov
    ports:
      - 9000:9000
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped
