name: Changelog Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for CHANGELOG.md changes
        run: |
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)

          if echo "$CHANGED" | grep -q "CHANGELOG.md"; then
            echo "CHANGELOG.md was updated. Check passed."
            exit 0
          else
            echo "CHANGELOG.md was not updated. Check failed."
            exit 1
          fi
