name: Coverage Check

on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: unsafe_secret_key
      RELOAD_REDIS_HOST: localhost
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install pipenv
        run: |
          python -m pip install --user pipenv

      - name: Install dependencies
        run: |
          python -m pipenv install --dev

      - name: Test
        run: |
          python -m pipenv run test

      - name: Coverage
        run: |
          python -m pipenv run ensure_coverage
